### ISSUE TITLE
How to report problems with the new CMake integration?

### ISSUE THREAD

**Issue by AliAskari** [Microsoft/VSLinux#181]
I installed preview 4 to try the new CMake integration with VC++ Linux. I am really excited about it but unfortunately after installing the preview everything broke. 

My stable, non-preview, installation of Visual Studio does not work properly any more, specifically the CMake integration, as it fails to find a compiler. The preview mode also does not work as expected, there are no CMake options when I right-click on my CMakeLists.txt. I have tried to reinstall/repair both products several times but it does not resolve my issues.

I assume these issues are not directly related to your team. Is there a way to get in touch with the CMake integration team?

**Comment by lukka** [comment]
@AliAskari  Please report here the error, this is the right channel indeed.

**Comment by AliAskari** [comment]
@lukka I see, OK. As I mentioned when I open Visual Studio Preview it does not have the CMake options

![image](https://user-images.githubusercontent.com/4864412/30242757-762c1eb0-956a-11e7-9164-515c3490188c.png)

I realized when I add the `CMakeSettings.json` the options appear, however I still cannot create the cache as the options are grayed out

![image](https://user-images.githubusercontent.com/4864412/30242774-a3706ebc-956a-11e7-910e-6333be9086a4.png)

I also cannot edit the CMakeSettings. When I click on the Change CMake Settings option I get this error:

![image](https://user-images.githubusercontent.com/4864412/30242779-cd935920-956a-11e7-954e-786f07a959a0.png)

I can provide more details, installation/update logs, if required.

**Comment by lukka** [comment]
@AliAskari could you try to repair your Visual Studio installation? If still not working, we need a way to reproduce it:
 - which version the Help->About dialog reports?
 - which workloads you installed?

**Comment by AliAskari** [comment]
@lukka I have repaired it multiple times and the repair seems to finish without any warnings but I am still experiencing the same issues.

- I am on the latest version **15.4.0 Preview 2.0**

![image](https://user-images.githubusercontent.com/4864412/30527794-5f0fbdd6-9bfa-11e7-8498-8cbd0765a894.png)

- I have **Desktop Development with C++** and **Linux development with C++** workloads along with the optional **Visual C++ tools for CMake and Linux** installed.

![vslinux_help](https://user-images.githubusercontent.com/4864412/30528143-fcee6586-9bfd-11e7-9025-ccd815297a33.gif)

**Comment by AliAskari** [comment]
@lukka Any updates on this issue?  I can provide logs or even find time for a remote session if required. Thanks!

**Comment by lukka** [comment]
@AliAskari thanks for your help. Could you please try the most recent version of [15.4 Preview ](https://www.visualstudio.com/vs/preview/) of VS? On 3rd Oct Preview 4 has been released. If the problem persist, we will likely try to collect and investigate on the log files.

**Comment by AliAskari** [comment]
I have updated to version 15.4 but I am still having a similar issue. 

If I do not select "Visual C++ tools for CMake and Linux" in the installer the Windows CMake integration works and when I add the Linux specific section to CMakeSettings.json I get a message that Visual Studio cannot successfully switch to the new configuration. However after installing the "Visual C++ tools for CMake and Linux" component the entire CMake integration stops working, both on Windows and Linux. 
The configuration menu does not show any of the names specified in CMakeSettings.json and there are no CMake menus or options.

![image](https://user-images.githubusercontent.com/4864412/31536858-28bbd44e-afce-11e7-86b6-e4be64685f7d.png)

![image](https://user-images.githubusercontent.com/4864412/31536897-5a22f396-afce-11e7-8a6e-a4207f4cd5a5.png)

Any tips?

**Comment by lukka** [comment]
@AliAskari please if you can, try the [VS Preview 15.5](https://blogs.msdn.microsoft.com/visualstudio/2017/10/11/visual-studio-2017-version-15-5-preview/), then close the issue if it is fixed. Thanks for you help by the way.

**Comment by AliAskari** [comment]
@lukka Yes, this problem is indeed resolved in 15.5. I also followed the steps mentioned in [this](https://developercommunity.visualstudio.com/content/problem/128569/cmake-unusable-after-upgrading-to-154.html) post and it resolves the problem even with version 15.4.

However I have CMake 3.10 installed on my machine and I am getting this error from Visual Studio 15.5:

     at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
       at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
       at libcmake.CMakeDaemonDriver.Expects(String message, String expectedMessage)
       at libcmake.CMakeDaemonDriver.<ShakeHandAsync>d__62.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at libcmake.Linux.RemoteCMakeDaemonDriver.<ShakeHandAsync>d__25.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at libcmake.Linux.RemoteCMakeLists.<ParseWithoutCacheAsync>d__19.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at libcmake.Linux.RemoteCMakeLists.<ParseAsync>d__11.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at libcmake.Linux.LocalCMakeLists.<ParseAsync>d__54.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at libcmake.Linux.LocalCMakeLists.<ParseAsync>d__53.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.VisualStudio.CMake.Project.CMakeListsUtils.<ParseAsync>d__12.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
       at Microsoft.VisualStudio.CMake.Project.CMakeListsCache.<ParseAsync>d__28.MoveNext()

and this from 15.4

    CMake version '3.10.20171014' is not supported. Please use 3.8 or newer

**Comment by AliAskari** [comment]
@lukka Any updates on these issues?

**Comment by lukka** [comment]
@AliAskari 3.8x and 3.9 are the only version supported currently, 3.10 is not currently supported yet.

**Comment by lukka** [comment]
@AliAskari  Correction for VS 2017 15.5 Preview 1: any CMake version greater than 3.8 should be supported. 

In case you are experiencing the error you mentioned above (the huge stack trace) with 15.5 Preview 1, could you please provide a small repro for the parsing error you discovered? Thanks a lot for you help.
