### ISSUE TITLE
CMake integration fails when multiple project() commands are used

### ISSUE THREAD

**Issue by devin122** [Microsoft/VSLinux#192]
Can't seem to get cmake builds working. Initially I had an issue even getting the thing to initialize, until I applied the fix outlined here: https://developercommunity.visualstudio.com/content/problem/120257/open-cmake-error-in-preview-version.html?childToView=121889#comment-121889
Now i can open the project, and it copies the files over and extracts the cmake information, however when I actually attempt to build a target, nothing happens, doesn't even seem to establish an ssh connection

Using
VS 2017 15.4.0 Preview 3
Ubuntu 16.04
CMake 3.8.2/3.9.0 (I've tried both)

Update: Moved to Preview 4 with the same results

**Comment by lukka** [comment]
@devin122 could you provide a repro?

**Comment by devin122** [comment]
@lukka  I've been attempting to build https://github.com/eclipse/omr
It does seem to be something about the codebase. I just created a simple hello-world application and it seems to build fine

**Comment by devin122** [comment]
Was playing around with things a bit more this morning (using different linux vm, but still Ubuntu 16.04 LTS) , and now I'm getting this:
```
1> -- Configuring done
1> -- Generating done
1> -- Build files have been written to: /var/tmp/build/c51a3e8b-f143-c031-9b1f-d63a3ea68378/build/Linux-Debug
1> Starting CMake target info extraction ...
1> Target info extraction done.
1> Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at libcmake.CMakeDaemonDriver.Expects(String message, String expectedMessage)
   at libcmake.CMakeDaemonDriver.<ShakeHandAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.RemoteCMakeDaemonDriver.<ShakeHandAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.RemoteCMakeLists.<ParseWithoutCacheAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.RemoteCMakeLists.<ParseAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.LocalCMakeLists.<ParseAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.LocalCMakeLists.<ParseAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsUtils.<ParseAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsCache.<ParseAsync>d__28.MoveNext()
```

**Comment by lukka** [comment]
@devin122 for the last reported error, please check whether cmake is version 3.9.0. 
If it is 3.9.1, that is currently not supported. We added a cmake version check for the upcoming 15.5 preview of VS.
If it is 3.9.0, we need to proceed forward with the investigation.

**Comment by devin122** [comment]
@lukka  for the last error i get it both on 3.8.2 and 3.9.0. For both vms I jsut downloaded the binary zips off of the cmake website, and unzipped them into my home folder (and updated `cmakeExecutable` in  CMakeSettings.json ). As for the first error I think I have it figured out (~~~just trying again from a clean workspace to verify~~ just verified). The issue appears to be with nested `project` commands. IE 
CMakeLists.txt:
```
project(foo VERSION 1.0 LANGUAGES C)
....
add_subdirectory(bar)
```

bar/CMakeLists.txt:
```
project(bar 1.0 LANGUAGES C)
....
```

Still trying to figure out the second error / what differences are between the vms

**Comment by dnakamura** [comment]
Digging into it I think the later error. ie 
```1> Input string was not in a correct format.```
is an unrelated error. The issue here is handling multiple `project()` commands

**Comment by devin122** [comment]
After further digging I think the second error is unrelated, will  open another issue after some more investigation

**Comment by lukka** [comment]
@devin122  Please could you give a try with VS 15.5 Preview?

With the following nested PROJECT() statements, no issues with VS 15.5 Preview:

./CMakeLists.txt
```
cmake_minimum_required(VERSION 3.8)
project(foo VERSION 1.0 LANGUAGES C)
add_executable(foo_exe foo.c)
```
./bar/CMakeLIsts.txt
```
project(mine VERSION 1.0 LANGUAGES C)
add_executable(bar_exe bar.c)
```

nit: Note that in your provide example you are missing "VERSION" keyword as argument to the PROJECT() command inside your inner CMakeLists.txt file.

**Comment by dosshell** [comment]
I have the same issue, with and without nested cmake projects.

WIndows Version 1709 (OS Build 16299. 15)
Visual Studio 15 Community 15.5 Preview 1.0
WSL Ubuntu 16.04 with cmake 3.8.2

Using native c++ development against WSL works.
Using cmake in WSL works.
I can also build the copied cmake files manually in WSL after the error.
Using x64-Debug taget works.
I have attached the error log when changing to Linux-Debug.
After the error I can not choose a startup-item (Only current document, but nothing happens if I select it).

Project configuration:

./bar.c
```
main(){}
```

./CMakeLists.txt
```
cmake_minimum_required(VERSION 3.8)
project(foo VERSION 1.0 LANGUAGES C)
add_executable(foo_exe foo.c)
```

Error log
```
Switching to configuration Linux-Debug....
1> 09:40:28: Copying files to remote machine...
1> 09:40:29: Finished copying files (elapsed time 00h:00m:01s:338ms).
1> /usr/local/bin/cmake -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE="Debug" "\var\tmp\src\1b6bd7df-2a05-083f-ba81-c420fbbd8286\Linux-Debug"
1> -- Configuring done
1> -- Generating done
1> -- Build files have been written to: /var/tmp/build/1b6bd7df-2a05-083f-ba81-c420fbbd8286/build/Linux-Debug
1> Starting CMake target info extraction ...
1> Target info extraction done.
1> Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at libcmake.CMakeDaemonDriver.Expects(String message, String expectedMessage)
   at libcmake.CMakeDaemonDriver.<ShakeHandAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.RemoteCMakeDaemonDriver.<ShakeHandAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.RemoteCMakeLists.<ParseWithoutCacheAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.RemoteCMakeLists.<ParseAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.LocalCMakeLists.<ParseAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.LocalCMakeLists.<ParseAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsUtils.<ParseAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsCache.<ParseAsync>d__28.MoveNext()
Configuration switch to Linux-Debug complete.
```

**Comment by devin122** [comment]
@lukka  Still getting the same issue with latest preview. Cache generation works fine, but when I try to build a target, nothing happens.
@dosshell  I think that is an unrelated issue. See #196

**Comment by lukka** [comment]
@devin122 could you please share:
  - sources (.cpp/.h./CMakeLists.txt files) to reproduce the problem;
  - the content of the cmakesettings.json file you are currently using;
Thanks for your support.

**Comment by devin122** [comment]
@lukka  Updated to 15.5 Preview 2 and it seems to be much better, although there are still issues.
Test project is: https://github.com/devin122/vs-cmake
- Building individual targets now seems to work, however "build all targets" doesn't seem to do anything
- The library defined in the sub-project shows up on the build menu twice
- Build all targets is only shown for whichever project comes first alphabetically 

![image](https://user-images.githubusercontent.com/2386562/32179772-99c7794a-bd66-11e7-8dc3-3512c65a2258.png)

Version Info:
```Microsoft Visual Studio Professional 2017 Preview (2)
Version 15.5.0 Preview 2.0
VisualStudio.15.Preview/15.5.0-pre.2.0+27019.1
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Professional

Visual Basic 2017   00370-10001-16822-AA879
Microsoft Visual Basic 2017

Visual C# 2017   00370-10001-16822-AA879
Microsoft Visual C# 2017

Visual C++ 2017   00370-10001-16822-AA879
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.0.31018.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Visual C++ for Linux Development   1.0.8
Visual C++ for Linux Development

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake
```

**Comment by lukka** [comment]
Build all target is present and works on VS2017 15.7. Closing this issue, feel free to reopen this or a new one if needed.
