### ISSUE TITLE
CMake crossplatform fails if the remote linux system has zsh as default shell

### ISSUE THREAD

**Issue by dosshell** [microsoft/VSLinux#217]
## A brief description
When using crossplattform cmake with a Linux system, the default shell can not be zsh or it will fail.

## Expected results
One should be allowed to have any default shell, for example zsh.

## Actual results (with build output window contents if applicable)
When trying to generate the CMakeLists.txt for the remote system, this is the output:
```
1> 18:00:25: Copying files to remote machine...
1> 18:00:25: Finished copying files (elapsed time 00h:00m:00s:002ms).
1> /usr/local/bin/cmake -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE="Debug" "\var\tmp\src\21b07445-abe3-c937-869f-439f032f7325\Linux-Debug"
1> -- Configuring done
1> -- Generating done
1> -- Build files have been written to: /var/tmp/build/21b07445-abe3-c937-869f-439f032f7325/build/Linux-Debug
1> Starting CMake target info extraction ...
1> Target info extraction done.
1> Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at libcmake.CMakeDaemonDriver.Expects(String message, String expectedMessage)
   at libcmake.CMakeDaemonDriver.<ShakeHandAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.RemoteCMakeDaemonDriver.<ShakeHandAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.RemoteCMakeLists.<ParseWithoutCacheAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.RemoteCMakeLists.<ParseAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.LocalCMakeLists.<ParseAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.LocalCMakeLists.<ParseAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsUtils.<ParseAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsCache.<ParseAsync>d__28.MoveNext()
```

## VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

Development system:
Visual Studio Version 15.5.0 Preview 2.0

Remote system is an Ubuntu 16.04.3 with cmake 3.8.2
```
$uname -a
 LAPTOP 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
$cmake --version
cmake version 3.8.2
$lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

## Steps required to reproduce the error
- Install zsh for the linux remote system
- Change default shell to zsh
- Add the remote system to VS (with the user that has zsh as default shell)
- Start ssh on the remote system
- Change Project Settings to target the remote system (Linux-Debug)
- Press CMake->Cache (Linux-Debug Only)->Generate->CMakeLists.txt

## Required packages and commands to install
```
apt-get install zsh
chsh -s /usr/bin/zsh
```

**Comment by itodirel** [comment]
similar to #28

**Comment by itodirel** [comment]
Tracked with https://developercommunity.visualstudio.com/idea/956725/compatibility-with-other-shells.html 

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.

**Comment by itodirel** [comment]
This is now fixed.
