### ISSUE TITLE
"Downloading and updating headers for IntelliSense" fails.

### ISSUE THREAD

**Issue by boskars** [Microsoft/VSLinux#274]
Visual Studio 15.7 prev 2

![image](https://user-images.githubusercontent.com/25032095/37826152-a5d9d500-2e92-11e8-9f8a-8874d8f949da.png)

The file contains:

liblinux.ExceptionBase: Exception of type 'liblinux.ExceptionBase' was thrown.
   at liblinux.Services.RemoteCompiler.CreateSysrootArchive()
   at liblinux.Services.RemoteCompiler.DownloadSysroot()
   at liblinux.Services.RemoteCompiler.CreateSysroot()
   at liblinux.Services.RemoteCompiler.CreateLocalSysroot()
   at Microsoft.VisualStudio.Linux.Package.Dialogs.HeaderUpdateDialog.<DownloadUpdate>b__13_0(Object _)

liblinux.ExceptionBase: Exception of type 'liblinux.ExceptionBase' was thrown.
   at liblinux.Services.RemoteCompiler.CreateSysrootArchive()
   at liblinux.Services.RemoteCompiler.DownloadSysroot()
   at liblinux.Services.RemoteCompiler.CreateSysroot()
   at liblinux.Services.RemoteCompiler.CreateLocalSysroot()
   at Microsoft.VisualStudio.Linux.Package.Dialogs.HeaderUpdateDialog.<DownloadUpdate>b__13_0(Object _)

liblinux.ExceptionBase: Exception of type 'liblinux.ExceptionBase' was thrown.
   at liblinux.Services.RemoteCompiler.CreateSysrootArchive()
   at liblinux.Services.RemoteCompiler.DownloadSysroot()
   at liblinux.Services.RemoteCompiler.CreateSysroot()
   at liblinux.Services.RemoteCompiler.CreateLocalSysroot()
   at Microsoft.VisualStudio.Linux.Package.Dialogs.HeaderUpdateDialog.<DownloadUpdate>b__13_0(Object _)

**Comment by lukka** [comment]
@boskars do you have 'zip' as a tool on the remote Linux box?

**Comment by itodirel** [comment]
Luca is correct, this happens because "zip" is not installed on the system. We are going to improve the message to just say that. Let us know if you have other suggestions.

**Comment by itodirel** [comment]
improved the error messages, now it will say exactly why in the dialog

**Comment by boskars** [comment]
We have a gzip tool on the device.  Does that count?

**Comment by itodirel** [comment]
today, we specifically need "zip", we're planning on using rsync in the future

**Comment by volzb** [comment]
hi i have zip installed but getting the same issues. is there anything else I can check?
