### ISSUE TITLE
PathTooLongException when downloading remote headers from openSuse 42.3

### ISSUE THREAD

**Issue by RobertK66** [Microsoft/VSLinux#295]
I am trying to setup Linux C++ development with a new Linux machine
OpenSuse 42.3 x64 (Gnome 3.20.2)
GCC 4.8-11.16
GDB 8.0.1-3.1
gdbserver not installed

Microsoft Visual Studio Professional 2017 Version 15.7.2 Release/15.7.2+27703.2018
Visual C++ 2017   00370-10001-03652-AA288
Visual C++ for Linux Development   1.0.9

The Download stops with "Path to long" Error message:
![image](https://user-images.githubusercontent.com/16986510/40486102-a2762a54-5f60-11e8-99d5-cc81d9da2e27.png)

The Logfile contains:
```
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at liblinux.Services.RemoteCompiler.UnpackSysrootArchiveRemovingDuplicates()
   at liblinux.Services.RemoteCompiler.DownloadSysroot()
   at liblinux.Services.RemoteCompiler.CreateSysroot()
   at liblinux.Services.RemoteCompiler.CreateLocalSysroot()
   at Microsoft.VisualStudio.Linux.Package.Dialogs.HeaderUpdateDialog.<>c__DisplayClass17_0.<DownloadUpdate>b__0(Object _)
```

It does finish the steps: Make ZIP- download ZIP
The Error occurs while extracting ZIP (somewhere after 1/4..1/3 of the files).
The line within the list of header caches should indicate successful Download but it stays gray (unticked) after the error message.

Unfortunately I can not find any hints where this Cache is going to be located, the specific path failing  and/or if there is some Setting to move it to any other shorter root path.....

**Comment by RobertK66** [comment]
Sorry,  I now found #281. Looked before but didn't see it :-(
So  I think this is a duplicate.
