### ISSUE TITLE
MSBUILD : error MSB6003: The specified task executable "cmd.exe" could not be run.

### ISSUE THREAD

**Issue by sebastue** [microsoft/VSLinux#297]
I try to build the release version of [Apche Celix](https://github.com/apache/celix) on a linux gcc x64 environment. When I build the project with the debug configuration, everything works. But when I switch to the release configuration I get the error: "MSBUILD : error MSB6003: The specified task executable "cmd.exe" could not be run. The working directory "C:\Users\...\\CMakeBuilds\\9d363044-432b-3834-bd9d-ee1bb0a15310\\build\\Linux-Release-x64" does not exist.".

System:
* VisualStudio.15.Release/15.6.7+27428.2043
* Visual C++ 2017   00369-60000-00001-AA915
* gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
* GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1

With the visual studio version 15.8.0 Preview 1.1 I can't reproduce the error because I get the following error during cache generation:
1> Target info extraction done.
1> Object reference not set to an instance of an object.
   at libcmake.CMakeTargetBase`1.SetTargetInfoAndSources[BacktraceProtocol](CMakeTargetJsonProtocol`1 info, CMakeProjectJsonProtocol`1 project, DebugTargetType DebugTargetType, IDictionary`2 traceDictionary)
   at libcmake.Linux.RemoteCMakeProject.GenerateTarget[BacktraceProtocol](CMakeTargetJsonProtocol`1 tgt, CMakeProjectJsonProtocol`1 curProject, DebugTargetType targetType, IDictionary`2 traceMap)
   at libcmake.CMakeProjectBase`3.UpdateListOfTargets[BacktraceProtocol](CMakeProjectJsonProtocol`1 curProject, Dictionary`2 pathToTargetMap, IDictionary`2 traceMap)
   at libcmake.CMakeProjectBase`3.<ExtractInfoGeneric>d__94`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.RemoteCMakeLists.<ExtractInfo>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.RemoteCMakeLists.<ParseWithoutCacheAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.LocalCMakeLists.<ParseAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.LocalCMakeLists.<ParseAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsUtils.<ParseAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsCache.<ParseAsync>d__28.MoveNext()

**Comment by yuehuang010** [comment]
Hello, What version of CMake are you using?  CMake 3.8 or 3.9 are the supported versions.

**Comment by sebastue** [comment]
I use cmake version 3.10.3.

**Comment by lukka** [comment]
@sebastue this was reported in #288 . The bug will be fixed in the next version of VS 15.8 Preview. Keeping the issue open until the preview version with the fix is released.

**Comment by sebastue** [comment]
I get the the same bug as in issue #288 when I use the newest version of visual studio. But does this bugfix also fix my problem with the release version (see above)?

**Comment by lukka** [comment]
@sebastue it should as the stack trace is identical. I keep this issue open, please report back your findings on VS 15.8 Preview 3 (not out yet).

**Comment by necktwi** [comment]
```
>------ Build started: Project: CMakeLists, Configuration: Debug ------
MSBUILD : error MSB6003: The specified task executable "cmd.exe" could not be run. The working directory "C:\Users\gowth\CMakeBuilds\-1507714211\build\Linux-Debug" does not exist.

```
I hope this is the same issue I encountered. The workaround mentioned at [#288](https://github.com/Microsoft/VSLinux/issues/288) didn't work.

**Comment by lukka** [comment]
@necktwi could you please provide a small project (i.e. cmakelists.txt and source code) to repro what you are seeing?

**Comment by necktwi** [comment]
I was able to repro in VS 15.8.0 Preview 5.0.

**Comment by flufy3d** [comment]
>------ 生成 已启动: 项目: CMakeLists，配置: Debug ------
MSBUILD : error MSB6003: 指定的任务可执行文件“cmd.exe”未能运行。工作目录“C:\Users\mibook\CMakeBuilds\-502117047\build\BitcoinSV”不存在。


same problem here too, vs version 15.9.12

**Comment by itodirel** [comment]
This works very fine now @sebastue here is an example of the project loaded, I only had to install two libraries with apt-get. We have made very significant changes and improvements since, please give our experience a try.

![image](https://user-images.githubusercontent.com/15239856/77510622-7cd26100-6e2c-11ea-82d4-bd17e70a9c44.png)

The demo described by @Necktwi  also works fine with no issues, I assume you have targeted Windows? I expect this should work for Linux as well, just need to copy Demo1, or open workspace instead of CMakePsuedoSubDirDemo.

![image](https://user-images.githubusercontent.com/15239856/77511021-5e209a00-6e2d-11ea-95fb-ad5029081e59.png)

Here is the example of that:

![image](https://user-images.githubusercontent.com/15239856/77511114-9922cd80-6e2d-11ea-888a-36d896cf6697.png)

For any comments, suggestions, issues, please open a ticket on the Developer Community.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
