### ISSUE TITLE
Encountered "CMake scanning exception Path must be rooted" while VS generating CMake cache.

### ISSUE THREAD

**Issue by necktwi** [Microsoft/VSLinux#311]
I have created a samba share of my Linux C++ project, mapped it to a network drive (Z:) and opened the "Z:\\RemoteCMakeProject\\CMakeLists.txt" with the Visual Studio so that sources don't have to be copied to remote Linux machine. So I have set "remoteCopySources": false in CMakeSettings.json

On generating CMake cache to refresh, CMake generator says:
...
...
1> -- Generating done
1> -- Build files have been written to: /home/ozfguah/Workspace/RemoteCMakeProject/Build/VS
1> Starting CMake target info extraction ...
1> Extracted includes paths.
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted global settings.
1> Extracted code model.
1> Collating data ...
1> Target info extraction done.
CMake scanning exception Path must be rooted
Parameter name: basePath at    at Microsoft.VisualStudio.Workspace.PathHelper.MakeRelative(String basePath, String path)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsUtils.ComputeTargetNames(Boolean singleton, ICMakeLists data, CMakeConfiguration config)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsScanner.<AddTargetsAndBuildConfigToFDV>d__162.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsScanner.<ComputeFileDataValues>d__153.MoveNext()

What does CMake scanning exception Path must be rooted mean? What should I do to cross this issue?

**Comment by rchiodo** [comment]
What you're attempting is not supported. It's confused over whether the cmake is local or remote. It's attempting to take your remote path and make it relative to your build root.

**Comment by itodirel** [comment]
We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here. For anything else, we recommend to please open a ticket on the Developer Community.
