### ISSUE TITLE
Can't download Qt headers for IntelliSense

### ISSUE THREAD

**Issue by jhattonKv** [microsoft/VSLinux#323]
When I try to download headers from a raspberry pi running raspbian pixel it always fails on unzipping the phonon folder in QT4 with an access denied error. 

"An error has occured. Access to the path 'C:\Users\jhatton\AppData\Local\Microsoft\Linux\Header Cache\1.0\-1040798696\usr\include\qt4\phonon\phonon' is denied.. Please see C:\Users\jhatton\AppData\Local\Temp\vslinux_header_update_log.txt for more information."

Contents of Log File:
System.UnauthorizedAccessException: Access to the path 'C:\Users\jhatton\AppData\Local\Microsoft\Linux\Header Cache\1.0\-1040798696\usr\include\qt4\phonon\phonon' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at liblinux.Services.RemoteCompiler.UnpackSysrootArchiveRemovingDuplicates()
   at liblinux.Services.RemoteCompiler.DownloadSysroot()
   at liblinux.Services.RemoteCompiler.CreateSysroot()
   at liblinux.Services.RemoteCompiler.CreateLocalSysroot()
   at Microsoft.VisualStudio.Linux.Package.Dialogs.HeaderUpdateDialog.<>c__DisplayClass17_0.<DownloadUpdate>b__0(Object _)

**Comment by lukka** [comment]
@jhattonKv could you please report that content of the log file? Thanks a lot.

**Comment by jhattonKv** [comment]
@lukka I have updated the original comment with the content of the log file

**Comment by lukka** [comment]
it looks like 

`C:\Users\jhatton\AppData\Local\Microsoft\Linux\Header Cache\1.0-1040798696\usr\include\qt4\phonon\phonon
`
is missing a separator as in :

`C:\Users\jhatton\AppData\Local\Microsoft\Linux\Header Cache\1.0\-1040798696\usr\include\qt4\phonon\phonon`

**Comment by itodirel** [comment]
We believe this issue was addressed, if you still have this issue, please open a issue to us on the Developer Community.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
