### ISSUE TITLE
VS 16.2  reports missing rsync during header download

### ISSUE THREAD

**Issue by ChakritRakuang** [microsoft/VSLinux#374]
![2019-07-30](https://user-images.githubusercontent.com/25774969/62072535-0bc0b680-b269-11e9-94e5-4998401727ce.png)

liblinux.ExceptionBase: Could not start the 'rsync' command on the remote host, please install it using your system package manager. Please see https://aka.ms/AA23jat for troubleshooting.
   at liblinux.Services.RsyncRemoteCompilerIOImpl.<DownloadDirectoriesAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at liblinux.Services.RemoteCompiler.<DownloadSysrootAsync>d__153.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at liblinux.Services.RemoteCompiler.<CreateSysrootAsync>d__187.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at liblinux.Services.RemoteCompiler.<CreateLocalSysrootAsync>d__148.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.Linux.Package.Dialogs.HeaderUpdateDialog.<DownloadUpdateAsync>d__18.MoveNext()

**Comment by ChakritRakuang** [comment]
[vslinux_header_update_log.txt](https://github.com/microsoft/VSLinux/files/3443751/vslinux_header_update_log.txt)

**Comment by ChakritRakuang** [comment]
Debian remote host

**Comment by itodirel** [comment]
We believe we addressed this issue since, it does not repro for us. If this is a problem for you, please open a issue for us on the Developer Community. 

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
